library(rjson)
cmdargs <- commandArgs( trailingOnly = TRUE)
df <-read.csv(cmdargs[1])
d <-lm(df)
coef_filename <-paste0(cmdargs[2], "_coefficients.json")
coef_filename <-paste0("regression_app/reg_results/", coef_filename)
write(toJSON(d$coefficients), coef_filename)
print(summary(d))
